[workspace]
members = ["primitives", "script", "guest", "guest_wrapper"]
resolver = "2"

[workspace.package]
license = "MIT"
edition = "2021"
authors = ["xavierdmello", "ratankaliani"]
homepage = "https://succinctlabs.github.io/op-succinct/"
repository = "https://github.com/succinctlabs/op-succinct"

[workspace.dependencies]
# risc0-helios
risc0-helios-script = { path = "script" }
risc0-helios-guest = { path = "guest" }
risc0-helios-primitives = { path = "primitives" }
risc0-helios-guest-wrapper = { path = "guest_wrapper" }

# helios
helios = { git = "https://github.com/a16z/helios", version = "0.7.0" }
helios-consensus-core = { git = "https://github.com/a16z/helios", version = "0.7.0" }
helios-ethereum = { git = "https://github.com/a16z/helios", version = "0.7.0" }

# general
dotenv = "0.15.0"
eyre = "0.6.12"
tokio = "1.38.0"
tracing = "0.1.37"
serde = { version = "1.0.203", features = ["derive"] }
ssz-rs = { package = "ssz_rs", version = "0.9.0" }
thiserror = "1.0.61"
zduny-wasm-timer = "0.2.8"
serde_cbor = "0.11.2"
hex = "0.4.3"
serde_json = "1.0.125"
alloy-sol-types = "0.7.7"
clap = { version = "4.5.9", features = ["derive"] }
log = "0.4.22"
env_logger = "0.11.3"
alloy-primitives = "0.7.7"
alloy = { version = "0.1.1", features = ["full"] }
anyhow = "1.0.86"
reqwest = "0.12.5"
tree_hash = "0.7.0"
serde_with = { version = "3.4.0", features = ["hex"] }
cargo_metadata = "0.18"
risc0-zkvm = "1.2.0"
risc0-build = "1.2.0"
risc0-zkp = { version = "1.2.0", default-features = false }
derive_more = { version = "1.0.0", features = ["debug", "into", "from", "into_iterator", "deref"] }
bytes = "1.8.0"
typenum = "1.17.0"

[patch.crates-io]
# From upstream: https://github.com/a16z/helios/blob/master/Cargo.toml#L116C29-L116C72
ethereum_hashing = { git = "https://github.com/ncitron/ethereum_hashing", rev = "7ee70944ed4fabe301551da8c447e4f4ae5e6c35" }
